#!/usr/bin/env bash
#
# Launch the corresponding bars on the primary and any secondary screen.
#
# Source: https://gitlab.com/BVollmerhaus/dotfiles/-/blob/master/config/polybar/launch_polybar

set -euo pipefail

# Retrieve interface names for network module
ETH="$(ip link | grep -m 1 -E '\b(en)' \
  | awk '{print substr($2, 1, length($2)-1)}')"
WIFI="$(ip link | grep -m 1 -E '\b(wl)' \
  | awk '{print substr($2, 1, length($2)-1)}')"

# Colors
NORMAL='\033[0m'
ITALIC='\033[3m'
RED='\033[1;31m'
BLUE='\033[1;34m'

readonly ETH
readonly WIFI
readonly NORMAL
readonly ITALIC
readonly RED
readonly BLUE

kill_running_instances() {
  pkill polybar || true
  while pgrep -u "$(id -u)" -x polybar >/dev/null; do
    sleep 0.25
  done
}

launch_bar() {
  MONITOR=$1 IF_ETH=${ETH} IF_WIFI=${WIFI} polybar "$2" 2>&1 | tee -a /tmp/polybar-"$2".log &
}

launch_secondary_bars() {
  IFS=$(printf '\n')
  for line in $(xrandr --listactivemonitors | sed '1d' | grep -v '\*'); do
    output=${line##* } # Get output name from last column
    printf "${BLUE}::${NORMAL} Launching secondary bars on %s...\n" "${output}"
    launch_bar "${output}" top-secondary
    launch_bar "${output}" bottom-secondary
  done
}

main() {
  if ! command -v xrandr >/dev/null 2>&1; then
    printf '%b' \
      "${RED}error:${NORMAL} ${ITALIC}xrandr${NORMAL} is required " \
      "for monitor detection but not installed.\n" >&2
    exit 1
  fi

  printf '%b' "Network interfaces: ${ITALIC}${ETH}${NORMAL}, ${ITALIC}${WIFI}${NORMAL}\n"

  printf '%b' "${BLUE}::${NORMAL} Terminating running bar instances...\n"
  kill_running_instances

  printf '%b' "${BLUE}::${NORMAL} Launching bars on primary monitor...\n"
  launch_bar '' top-primary
  launch_bar '' bottom-primary
}

main

# kak:filetype=sh
